---
baseURL: "/manual/develop/"
languageCode: "en-us"
title: "Flowee BPMS documentation"
theme: "camunda"

blackfriday:
  plainIDAnchors: true

params:
  canonicalBasePath: "https://docs.camunda.org"
  sections:
    - id: "get-started"
      name: "Get Started"
      url: "/get-started"
    - id: "manual"
      name: "Flowee BPMS"
      url: "/manual"
    - id: "optimize"
      name: "Optimize"
      url: "/optimize"
    - id: 'cawemo'
      name: 'Cawemo'
      url: '/cawemo'
    - id: "enterprise"
      name: "Enterprise"
      url: "/enterprise"
    - id: "security"
      name: "Security"
      url: "/security"
  section:
    id: "manual"
    version: "develop"
    versionAlias: "0.7"
    versions:
      - "latest"
      - "0.5"
      - "develop"
  github:
    repositoryName: "camunda/camunda-docs-manual"
    branch: "master"

outputs:
  home:
    - "HTML"
    - "RSS"
  section:
    - "HTML"

disableKinds:
- taxonomy
- taxonomyTerm
...
