---
baseURL: "/"
languageCode: "en-us"
title: "Flowee BPMS documentation"
theme: "flowee"

blackfriday:
  plainIDAnchors: true

params:
  canonicalBasePath: "https://bpms.finture.com"
  sections:
    - id: "get-started"
      name: "Get Started"
      url: "/get-started"
    - id: "manual"
      name: "Flowee BPMS"
      url: "/"
    - id: "enterprise"
      name: "Enterprise"
      url: "/enterprise"
    - id: "security"
      name: "Security"
      url: "/security"
  section:
    id: "manual"
    version: "develop"
    versionAlias: "0.7"
    versions:
      - "latest"
      - "develop"
  github:
    repositoryName: "flowee/flowee-bpms-docs-manual"
    branch: "master"

outputs:
  home:
    - "HTML"
    - "RSS"
  section:
    - "HTML"

disableKinds:
- taxonomy
- taxonomyTerm
...
