---
baseURL: "/security/"
languageCode: "en-us"
title: "Product Security Guide"
theme: "flowee"

blackfriday:
  plainIDAnchors: true

params:
  canonicalBasePath: "https://bpms.finture.com"
  sections:
    - id: "get-started"
      name: "Get Started"
      url: "/get-started"
    - id: "manual"
      name: "Flowee BPMS"
      url: "/"
    - id: "security"
      name: "Security"
      url: "/security"
  section:
    id: "security"
  github:
    repositoryName: "flowee-bpms/flowee-docs-static"
    branch: "master/security"

outputs:
  home:
    - "HTML"
    - "RSS"
  section:
    - "HTML"

disableKinds:
- taxonomy
- taxonomyTerm
...
